package cn.com.jy.hotel.domain.system;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysErrorLog generated by hbm2java
 */
@Entity
@Table(name = "sys_error_log", catalog = "hotel")
public class SysErrorLog implements java.io.Serializable {

	private Long id;
	private Date eventTime;
	private String ipAddress;
	private Integer operatorId;
	private String description;

	public SysErrorLog() {
	}

	public SysErrorLog(Date eventTime) {
		this.eventTime = eventTime;
	}

	public SysErrorLog(Date eventTime, String ipAddress, Integer operatorId,
			String description) {
		this.eventTime = eventTime;
		this.ipAddress = ipAddress;
		this.operatorId = operatorId;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventTime", nullable = false, length = 19)
	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Column(name = "ip_address")
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "operator_id")
	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
