package cn.com.jy.hotel.domain.system;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysOperator generated by hbm2java
 */
@Entity
@Table(name = "sys_operator", catalog = "hotel")
public class SysOperator implements java.io.Serializable {

	private Integer id;
	private SysRole sysRole;
	private short operatorNumber;
	private String operatorName;
	private String operatorPwd;
	private String pwdSalt;
	private byte status;
	private Set<SysOperatorLog> sysOperatorLogs = new HashSet<SysOperatorLog>(0);

	public SysOperator() {
	}

	public SysOperator(SysRole sysRole, short operatorNumber,
			String operatorName, String operatorPwd, String pwdSalt, byte status) {
		this.sysRole = sysRole;
		this.operatorNumber = operatorNumber;
		this.operatorName = operatorName;
		this.operatorPwd = operatorPwd;
		this.pwdSalt = pwdSalt;
		this.status = status;
	}

	public SysOperator(SysRole sysRole, short operatorNumber,
			String operatorName, String operatorPwd, String pwdSalt,
			byte status, Set<SysOperatorLog> sysOperatorLogs) {
		this.sysRole = sysRole;
		this.operatorNumber = operatorNumber;
		this.operatorName = operatorName;
		this.operatorPwd = operatorPwd;
		this.pwdSalt = pwdSalt;
		this.status = status;
		this.sysOperatorLogs = sysOperatorLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sys_role_id", nullable = false)
	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	@Column(name = "operator_number", nullable = false)
	public short getOperatorNumber() {
		return this.operatorNumber;
	}

	public void setOperatorNumber(short operatorNumber) {
		this.operatorNumber = operatorNumber;
	}

	@Column(name = "operator_name", nullable = false, length = 64)
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "operator_pwd", nullable = false, length = 128)
	public String getOperatorPwd() {
		return this.operatorPwd;
	}

	public void setOperatorPwd(String operatorPwd) {
		this.operatorPwd = operatorPwd;
	}

	@Column(name = "pwd_salt", nullable = false, length = 128)
	public String getPwdSalt() {
		return this.pwdSalt;
	}

	public void setPwdSalt(String pwdSalt) {
		this.pwdSalt = pwdSalt;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysOperator")
	public Set<SysOperatorLog> getSysOperatorLogs() {
		return this.sysOperatorLogs;
	}

	public void setSysOperatorLogs(Set<SysOperatorLog> sysOperatorLogs) {
		this.sysOperatorLogs = sysOperatorLogs;
	}

}
