package cn.com.jy.hotel.domain.system;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysOperatorLog generated by hbm2java
 */
@Entity
@Table(name = "sys_operator_log", catalog = "hotel")
public class SysOperatorLog implements java.io.Serializable {

	private Long id;
	private SysOperator sysOperator;
	private Date eventTime;
	private String description;
	private String ipAddress;

	public SysOperatorLog() {
	}

	public SysOperatorLog(SysOperator sysOperator, Date eventTime,
			String description) {
		this.sysOperator = sysOperator;
		this.eventTime = eventTime;
		this.description = description;
	}

	public SysOperatorLog(SysOperator sysOperator, Date eventTime,
			String description, String ipAddress) {
		this.sysOperator = sysOperator;
		this.eventTime = eventTime;
		this.description = description;
		this.ipAddress = ipAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operator_id", nullable = false)
	public SysOperator getSysOperator() {
		return this.sysOperator;
	}

	public void setSysOperator(SysOperator sysOperator) {
		this.sysOperator = sysOperator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventTime", nullable = false, length = 19)
	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ip_address")
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
