package cn.com.jy.hotel.domain.system;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysPrivilege generated by hbm2java
 */
@Entity
@Table(name = "sys_privilege", catalog = "hotel", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SysPrivilege implements java.io.Serializable {

	private Short id;
	private String name;
	private String description;
	private Set<SysRole> sysRoles = new HashSet<SysRole>(0);

	public SysPrivilege() {
	}

	public SysPrivilege(String name) {
		this.name = name;
	}

	public SysPrivilege(String name, String description, Set<SysRole> sysRoles) {
		this.name = name;
		this.description = description;
		this.sysRoles = sysRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY,mappedBy="sysPrivileges")
/*	@JoinTable(name = "sys_role_privilege", catalog = "hotel", joinColumns = { @JoinColumn(name = "privilege_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
*/	public Set<SysRole> getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(Set<SysRole> sysRoles) {
		this.sysRoles = sysRoles;
	}

}
