package cn.com.jy.hotel.domain.system;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", catalog = "hotel", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SysRole implements java.io.Serializable {

	private Short id;
	private String name;
	private String description;
	private Set<SysOperator> sysOperators = new HashSet<SysOperator>(0);
	private Set<SysPrivilege> sysPrivileges = new HashSet<SysPrivilege>(0);

	public SysRole() {
	}

	public SysRole(String name) {
		this.name = name;
	}

	public SysRole(String name, String description,
			Set<SysOperator> sysOperators, Set<SysPrivilege> sysPrivileges) {
		this.name = name;
		this.description = description;
		this.sysOperators = sysOperators;
		this.sysPrivileges = sysPrivileges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysOperator> getSysOperators() {
		return this.sysOperators;
	}

	public void setSysOperators(Set<SysOperator> sysOperators) {
		this.sysOperators = sysOperators;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "sys_role_privilege", catalog = "hotel", joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "privilege_id", nullable = false, updatable = false) })
	public Set<SysPrivilege> getSysPrivileges() {
		return this.sysPrivileges;
	}

	public void setSysPrivileges(Set<SysPrivilege> sysPrivileges) {
		this.sysPrivileges = sysPrivileges;
	}

}
