package cn.com.jy.hotel.domain.system;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysVariable generated by hbm2java
 */
@Entity
@Table(name = "sys_variable", catalog = "hotel")
public class SysVariable implements java.io.Serializable {

	private String varName;
	private String varValue;

	public SysVariable() {
	}

	public SysVariable(String varName) {
		this.varName = varName;
	}

	public SysVariable(String varName, String varValue) {
		this.varName = varName;
		this.varValue = varValue;
	}

	@Id
	@Column(name = "var_name", unique = true, nullable = false, length = 128)
	public String getVarName() {
		return this.varName;
	}

	public void setVarName(String varName) {
		this.varName = varName;
	}

	@Column(name = "var_value", length = 128)
	public String getVarValue() {
		return this.varValue;
	}

	public void setVarValue(String varValue) {
		this.varValue = varValue;
	}

}
