package cn.com.jy.hotel.domain.room;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RBookroomDetail generated by hbm2java
 */
@Entity
@Table(name = "r_bookroom_detail", catalog = "hotel")
public class RBookroomDetail implements java.io.Serializable {

	private Long id;
	private RBookroomType RBookroomType;
	private long roomId;

	public RBookroomDetail() {
	}

	public RBookroomDetail(RBookroomType RBookroomType, long roomId) {
		this.RBookroomType = RBookroomType;
		this.roomId = roomId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookroom_type_id", nullable = false)
	public RBookroomType getRBookroomType() {
		return this.RBookroomType;
	}

	public void setRBookroomType(RBookroomType RBookroomType) {
		this.RBookroomType = RBookroomType;
	}

	@Column(name = "room_id", nullable = false)
	public long getRoomId() {
		return this.roomId;
	}

	public void setRoomId(long roomId) {
		this.roomId = roomId;
	}

}
