package cn.com.jy.hotel.domain.room;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import cn.com.jy.hotel.domain.guest.GGuestRoomDetail;

/**
 * RRoom generated by hbm2java
 */
@Entity
@Table(name = "r_room", catalog = "hotel")
public class RRoom implements java.io.Serializable {

	private Integer id;
	private RRoomGroup RRoomGroup;
	private RRoomType RRoomType;
	private String roomNumber;
	private byte roomStatus;
	private Long guestRoomDetailId;
	private Set<GGuestRoomDetail> GGuestRoomDetails = new HashSet<GGuestRoomDetail>(
			0);

	public RRoom() {
	}

	public RRoom(RRoomGroup RRoomGroup, RRoomType RRoomType, String roomNumber,
			byte roomStatus) {
		this.RRoomGroup = RRoomGroup;
		this.RRoomType = RRoomType;
		this.roomNumber = roomNumber;
		this.roomStatus = roomStatus;
	}

	public RRoom(RRoomGroup RRoomGroup, RRoomType RRoomType, String roomNumber,
			byte roomStatus, Long guestRoomDetailId,
			Set<GGuestRoomDetail> GGuestRoomDetails) {
		this.RRoomGroup = RRoomGroup;
		this.RRoomType = RRoomType;
		this.roomNumber = roomNumber;
		this.roomStatus = roomStatus;
		this.guestRoomDetailId = guestRoomDetailId;
		this.GGuestRoomDetails = GGuestRoomDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public RRoomGroup getRRoomGroup() {
		return this.RRoomGroup;
	}

	public void setRRoomGroup(RRoomGroup RRoomGroup) {
		this.RRoomGroup = RRoomGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_type_id", nullable = false)
	public RRoomType getRRoomType() {
		return this.RRoomType;
	}

	public void setRRoomType(RRoomType RRoomType) {
		this.RRoomType = RRoomType;
	}

	@Column(name = "room_number", nullable = false, length = 32)
	public String getRoomNumber() {
		return this.roomNumber;
	}

	public void setRoomNumber(String roomNumber) {
		this.roomNumber = roomNumber;
	}

	@Column(name = "room_status", nullable = false)
	public byte getRoomStatus() {
		return this.roomStatus;
	}

	public void setRoomStatus(byte roomStatus) {
		this.roomStatus = roomStatus;
	}

	@Column(name = "guest_room_detail_id")
	public Long getGuestRoomDetailId() {
		return this.guestRoomDetailId;
	}

	public void setGuestRoomDetailId(Long guestRoomDetailId) {
		this.guestRoomDetailId = guestRoomDetailId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "RRoom")
	public Set<GGuestRoomDetail> getGGuestRoomDetails() {
		return this.GGuestRoomDetails;
	}

	public void setGGuestRoomDetails(Set<GGuestRoomDetail> GGuestRoomDetails) {
		this.GGuestRoomDetails = GGuestRoomDetails;
	}

}
