package cn.com.jy.hotel.domain.gain;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HIncomeMonth generated by hbm2java
 */
@Entity
@Table(name = "h_income_month", catalog = "hotel")
public class HIncomeMonth implements java.io.Serializable {

	private Date dayTime;
	private BigDecimal income;
	private BigDecimal cost;
	private BigDecimal profit;

	public HIncomeMonth() {
	}

	public HIncomeMonth(Date dayTime, BigDecimal income, BigDecimal cost,
			BigDecimal profit) {
		this.dayTime = dayTime;
		this.income = income;
		this.cost = cost;
		this.profit = profit;
	}

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "dayTime", unique = true, nullable = false, length = 10)
	public Date getDayTime() {
		return this.dayTime;
	}

	public void setDayTime(Date dayTime) {
		this.dayTime = dayTime;
	}

	@Column(name = "income", nullable = false, precision = 14)
	public BigDecimal getIncome() {
		return this.income;
	}

	public void setIncome(BigDecimal income) {
		this.income = income;
	}

	@Column(name = "cost", nullable = false, precision = 14)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "profit", nullable = false, precision = 14)
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

}
