package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GCheckIn generated by hbm2java
 */
@Entity
@Table(name = "g_check_in", catalog = "hotel")
public class GCheckIn implements java.io.Serializable {

	private Long id;
	private byte status;
	private byte discount;
	private BigDecimal allCost;
	private BigDecimal vipPay;
	private BigDecimal cashPay;
	private BigDecimal webPay;
	private BigDecimal shouldPay;
	private BigDecimal hadPay;
	private Date startTime;
	private Date actuallyEndTime;
	private BigDecimal deposit;
	private BigDecimal depositReturn;
	private String depositCostDesc;
	private Long vipId;
	private Set<GGuestDetail> GGuestDetails = new HashSet<GGuestDetail>(0);
	private Set<GGuestRoomDetail> GGuestRoomDetails = new HashSet<GGuestRoomDetail>(
			0);
	private Set<GCheckinGoodsCost> GCheckinGoodsCosts = new HashSet<GCheckinGoodsCost>(
			0);

	public GCheckIn() {
	}

	public GCheckIn(byte status, byte discount, BigDecimal vipPay,
			BigDecimal cashPay, BigDecimal webPay, Date startTime,
			BigDecimal deposit, BigDecimal depositReturn) {
		this.status = status;
		this.discount = discount;
		this.vipPay = vipPay;
		this.cashPay = cashPay;
		this.webPay = webPay;
		this.startTime = startTime;
		this.deposit = deposit;
		this.depositReturn = depositReturn;
	}

	public GCheckIn(byte status, byte discount, BigDecimal allCost,
			BigDecimal vipPay, BigDecimal cashPay, BigDecimal webPay,
			BigDecimal shouldPay, BigDecimal hadPay, Date startTime,
			Date actuallyEndTime, BigDecimal deposit, BigDecimal depositReturn,
			String depositCostDesc, Long vipId,
			Set<GGuestDetail> GGuestDetails,
			Set<GGuestRoomDetail> GGuestRoomDetails,
			Set<GCheckinGoodsCost> GCheckinGoodsCosts) {
		this.status = status;
		this.discount = discount;
		this.allCost = allCost;
		this.vipPay = vipPay;
		this.cashPay = cashPay;
		this.webPay = webPay;
		this.shouldPay = shouldPay;
		this.hadPay = hadPay;
		this.startTime = startTime;
		this.actuallyEndTime = actuallyEndTime;
		this.deposit = deposit;
		this.depositReturn = depositReturn;
		this.depositCostDesc = depositCostDesc;
		this.vipId = vipId;
		this.GGuestDetails = GGuestDetails;
		this.GGuestRoomDetails = GGuestRoomDetails;
		this.GCheckinGoodsCosts = GCheckinGoodsCosts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "discount", nullable = false)
	public byte getDiscount() {
		return this.discount;
	}

	public void setDiscount(byte discount) {
		this.discount = discount;
	}

	@Column(name = "allCost", precision = 11)
	public BigDecimal getAllCost() {
		return this.allCost;
	}

	public void setAllCost(BigDecimal allCost) {
		this.allCost = allCost;
	}

	@Column(name = "vipPay", nullable = false, precision = 11)
	public BigDecimal getVipPay() {
		return this.vipPay;
	}

	public void setVipPay(BigDecimal vipPay) {
		this.vipPay = vipPay;
	}

	@Column(name = "cashPay", nullable = false, precision = 11)
	public BigDecimal getCashPay() {
		return this.cashPay;
	}

	public void setCashPay(BigDecimal cashPay) {
		this.cashPay = cashPay;
	}

	@Column(name = "webPay", nullable = false, precision = 11)
	public BigDecimal getWebPay() {
		return this.webPay;
	}

	public void setWebPay(BigDecimal webPay) {
		this.webPay = webPay;
	}

	@Column(name = "shouldPay", precision = 11)
	public BigDecimal getShouldPay() {
		return this.shouldPay;
	}

	public void setShouldPay(BigDecimal shouldPay) {
		this.shouldPay = shouldPay;
	}

	@Column(name = "hadPay", precision = 11)
	public BigDecimal getHadPay() {
		return this.hadPay;
	}

	public void setHadPay(BigDecimal hadPay) {
		this.hadPay = hadPay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startTime", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actuallyEndTime", length = 19)
	public Date getActuallyEndTime() {
		return this.actuallyEndTime;
	}

	public void setActuallyEndTime(Date actuallyEndTime) {
		this.actuallyEndTime = actuallyEndTime;
	}

	@Column(name = "deposit", nullable = false, precision = 11)
	public BigDecimal getDeposit() {
		return this.deposit;
	}

	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

	@Column(name = "deposit_return", nullable = false, precision = 11)
	public BigDecimal getDepositReturn() {
		return this.depositReturn;
	}

	public void setDepositReturn(BigDecimal depositReturn) {
		this.depositReturn = depositReturn;
	}

	@Column(name = "deposit_cost_desc", length = 65535)
	public String getDepositCostDesc() {
		return this.depositCostDesc;
	}

	public void setDepositCostDesc(String depositCostDesc) {
		this.depositCostDesc = depositCostDesc;
	}

	@Column(name = "vip_id")
	public Long getVipId() {
		return this.vipId;
	}

	public void setVipId(Long vipId) {
		this.vipId = vipId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "GCheckIn")
	public Set<GGuestDetail> getGGuestDetails() {
		return this.GGuestDetails;
	}

	public void setGGuestDetails(Set<GGuestDetail> GGuestDetails) {
		this.GGuestDetails = GGuestDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "GCheckIn")
	public Set<GGuestRoomDetail> getGGuestRoomDetails() {
		return this.GGuestRoomDetails;
	}

	public void setGGuestRoomDetails(Set<GGuestRoomDetail> GGuestRoomDetails) {
		this.GGuestRoomDetails = GGuestRoomDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "GCheckIn")
	public Set<GCheckinGoodsCost> getGCheckinGoodsCosts() {
		return this.GCheckinGoodsCosts;
	}

	public void setGCheckinGoodsCosts(Set<GCheckinGoodsCost> GCheckinGoodsCosts) {
		this.GCheckinGoodsCosts = GCheckinGoodsCosts;
	}

}
