package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GCheckinGoodsCost generated by hbm2java
 */
@Entity
@Table(name = "g_checkin_goods_cost", catalog = "hotel")
public class GCheckinGoodsCost implements java.io.Serializable {

	private Long id;
	private GCheckIn GCheckIn;
	private int goodsSaleId;
	private int buyCount;
	private BigDecimal cost;

	public GCheckinGoodsCost() {
	}

	public GCheckinGoodsCost(GCheckIn GCheckIn, int goodsSaleId, int buyCount,
			BigDecimal cost) {
		this.GCheckIn = GCheckIn;
		this.goodsSaleId = goodsSaleId;
		this.buyCount = buyCount;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "check_in_id", nullable = false)
	public GCheckIn getGCheckIn() {
		return this.GCheckIn;
	}

	public void setGCheckIn(GCheckIn GCheckIn) {
		this.GCheckIn = GCheckIn;
	}

	@Column(name = "goods_sale_id", nullable = false)
	public int getGoodsSaleId() {
		return this.goodsSaleId;
	}

	public void setGoodsSaleId(int goodsSaleId) {
		this.goodsSaleId = goodsSaleId;
	}

	@Column(name = "buyCount", nullable = false)
	public int getBuyCount() {
		return this.buyCount;
	}

	public void setBuyCount(int buyCount) {
		this.buyCount = buyCount;
	}

	@Column(name = "cost", nullable = false, precision = 11)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

}
