package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GGoodsProvide generated by hbm2java
 */
@Entity
@Table(name = "g_goods_provide", catalog = "hotel", uniqueConstraints = @UniqueConstraint(columnNames = "item_name"))
public class GGoodsProvide implements java.io.Serializable {

	private Integer id;
	private String itemName;
	private String item;
	private int stock;
	private BigDecimal cost;

	public GGoodsProvide() {
	}

	public GGoodsProvide(String itemName, int stock, BigDecimal cost) {
		this.itemName = itemName;
		this.stock = stock;
		this.cost = cost;
	}

	public GGoodsProvide(String itemName, String item, int stock,
			BigDecimal cost) {
		this.itemName = itemName;
		this.item = item;
		this.stock = stock;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "item_name", unique = true, nullable = false, length = 128)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item", length = 65535)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@Column(name = "cost", nullable = false, precision = 11)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

}
