package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GGoodsSaleType generated by hbm2java
 */
@Entity
@Table(name = "g_goods_sale_type", catalog = "hotel", uniqueConstraints = @UniqueConstraint(columnNames = "type_name"))
public class GGoodsSaleType implements java.io.Serializable {

	private Short id;
	private String typeName;
	private byte status;
	private Set<GGoodsSale> GGoodsSales = new HashSet<GGoodsSale>(0);

	public GGoodsSaleType() {
	}

	public GGoodsSaleType(String typeName, byte status) {
		this.typeName = typeName;
		this.status = status;
	}

	public GGoodsSaleType(String typeName, byte status,
			Set<GGoodsSale> GGoodsSales) {
		this.typeName = typeName;
		this.status = status;
		this.GGoodsSales = GGoodsSales;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "type_name", unique = true, nullable = false, length = 64)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "GGoodsSaleType")
	public Set<GGoodsSale> getGGoodsSales() {
		return this.GGoodsSales;
	}

	public void setGGoodsSales(Set<GGoodsSale> GGoodsSales) {
		this.GGoodsSales = GGoodsSales;
	}

}
