package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GGoodsSale generated by hbm2java
 */
@Entity
@Table(name = "g_goods_sale", catalog = "hotel")
public class GGoodsSale implements java.io.Serializable {

	private Integer id;
	private GGoodsSaleType GGoodsSaleType;
	private String itemName;
	private String itemDesc;
	private BigDecimal cost;
	private int stock;
	private BigDecimal salePrice;

	public GGoodsSale() {
	}

	public GGoodsSale(GGoodsSaleType GGoodsSaleType, int stock) {
		this.GGoodsSaleType = GGoodsSaleType;
		this.stock = stock;
	}

	public GGoodsSale(GGoodsSaleType GGoodsSaleType, String itemName,
			String itemDesc, BigDecimal cost, int stock, BigDecimal salePrice) {
		this.GGoodsSaleType = GGoodsSaleType;
		this.itemName = itemName;
		this.itemDesc = itemDesc;
		this.cost = cost;
		this.stock = stock;
		this.salePrice = salePrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_type_id", nullable = false)
	public GGoodsSaleType getGGoodsSaleType() {
		return this.GGoodsSaleType;
	}

	public void setGGoodsSaleType(GGoodsSaleType GGoodsSaleType) {
		this.GGoodsSaleType = GGoodsSaleType;
	}

	@Column(name = "item_name", length = 128)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_desc", length = 65535)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "cost", precision = 11)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@Column(name = "salePrice", precision = 11)
	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

}
