package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cn.com.jy.hotel.domain.room.RRoom;
import cn.com.jy.hotel.domain.room.RRoomPayMethod;

/**
 * GGuestRoomDetail generated by hbm2java
 */
@Entity
@Table(name = "g_guest_room_detail", catalog = "hotel")
public class GGuestRoomDetail implements java.io.Serializable {

	private Long id;
	private GCheckIn GCheckIn;
	private RRoom RRoom;
	private RRoomPayMethod RRoomPayMethod;
	private Date startTime;
	private Date endTime;
	private Date actuallyEndTime;

	public GGuestRoomDetail() {
	}

	public GGuestRoomDetail(GCheckIn GCheckIn, Date startTime, Date endTime) {
		this.GCheckIn = GCheckIn;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public GGuestRoomDetail(GCheckIn GCheckIn, RRoom RRoom,
			RRoomPayMethod RRoomPayMethod, Date startTime, Date endTime,
			Date actuallyEndTime) {
		this.GCheckIn = GCheckIn;
		this.RRoom = RRoom;
		this.RRoomPayMethod = RRoomPayMethod;
		this.startTime = startTime;
		this.endTime = endTime;
		this.actuallyEndTime = actuallyEndTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "check_in_id", nullable = false)
	public GCheckIn getGCheckIn() {
		return this.GCheckIn;
	}

	public void setGCheckIn(GCheckIn GCheckIn) {
		this.GCheckIn = GCheckIn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id")
	public RRoom getRRoom() {
		return this.RRoom;
	}

	public void setRRoom(RRoom RRoom) {
		this.RRoom = RRoom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payMethod_id")
	public RRoomPayMethod getRRoomPayMethod() {
		return this.RRoomPayMethod;
	}

	public void setRRoomPayMethod(RRoomPayMethod RRoomPayMethod) {
		this.RRoomPayMethod = RRoomPayMethod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startTime", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endTime", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actuallyEndTime", length = 19)
	public Date getActuallyEndTime() {
		return this.actuallyEndTime;
	}

	public void setActuallyEndTime(Date actuallyEndTime) {
		this.actuallyEndTime = actuallyEndTime;
	}

}
