package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GVip generated by hbm2java
 */
@Entity
@Table(name = "g_vip", catalog = "hotel", uniqueConstraints = @UniqueConstraint(columnNames = "vip_phone"))
public class GVip implements java.io.Serializable {

	private Long id;
	private GVipType GVipType;
	private String vipName;
	private BigDecimal blances;
	private String remark;
	private String vipIdCard;
	private byte status;
	private String vipPhone;
	private long points;
	private Set<GVipLog> GVipLogs = new HashSet<GVipLog>(0);

	public GVip() {
	}

	public GVip(GVipType GVipType, String vipName, BigDecimal blances,
			String vipIdCard, byte status, String vipPhone, long points) {
		this.GVipType = GVipType;
		this.vipName = vipName;
		this.blances = blances;
		this.vipIdCard = vipIdCard;
		this.status = status;
		this.vipPhone = vipPhone;
		this.points = points;
	}

	public GVip(GVipType GVipType, String vipName, BigDecimal blances,
			String remark, String vipIdCard, byte status, String vipPhone,
			long points, Set<GVipLog> GVipLogs) {
		this.GVipType = GVipType;
		this.vipName = vipName;
		this.blances = blances;
		this.remark = remark;
		this.vipIdCard = vipIdCard;
		this.status = status;
		this.vipPhone = vipPhone;
		this.points = points;
		this.GVipLogs = GVipLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vip_type_id", nullable = false)
	public GVipType getGVipType() {
		return this.GVipType;
	}

	public void setGVipType(GVipType GVipType) {
		this.GVipType = GVipType;
	}

	@Column(name = "vip_name", nullable = false, length = 32)
	public String getVipName() {
		return this.vipName;
	}

	public void setVipName(String vipName) {
		this.vipName = vipName;
	}

	@Column(name = "blances", nullable = false, precision = 11)
	public BigDecimal getBlances() {
		return this.blances;
	}

	public void setBlances(BigDecimal blances) {
		this.blances = blances;
	}

	@Column(name = "remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "vip_idCard", nullable = false, length = 20)
	public String getVipIdCard() {
		return this.vipIdCard;
	}

	public void setVipIdCard(String vipIdCard) {
		this.vipIdCard = vipIdCard;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "vip_phone", unique = true, nullable = false, length = 11)
	public String getVipPhone() {
		return this.vipPhone;
	}

	public void setVipPhone(String vipPhone) {
		this.vipPhone = vipPhone;
	}

	@Column(name = "points", nullable = false)
	public long getPoints() {
		return this.points;
	}

	public void setPoints(long points) {
		this.points = points;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "GVip")
	public Set<GVipLog> getGVipLogs() {
		return this.GVipLogs;
	}

	public void setGVipLogs(Set<GVipLog> GVipLogs) {
		this.GVipLogs = GVipLogs;
	}

}
