package cn.com.jy.hotel.domain.guest;

// Generated 2016-4-14 2:43:54 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GVipLog generated by hbm2java
 */
@Entity
@Table(name = "g_vip_log", catalog = "hotel")
public class GVipLog implements java.io.Serializable {

	private Long id;
	private GVip GVip;
	private String logDetail;
	private Date logTime;

	public GVipLog() {
	}

	public GVipLog(GVip GVip, String logDetail, Date logTime) {
		this.GVip = GVip;
		this.logDetail = logDetail;
		this.logTime = logTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vip_id", nullable = false)
	public GVip getGVip() {
		return this.GVip;
	}

	public void setGVip(GVip GVip) {
		this.GVip = GVip;
	}

	@Column(name = "log_detail", nullable = false, length = 65535)
	public String getLogDetail() {
		return this.logDetail;
	}

	public void setLogDetail(String logDetail) {
		this.logDetail = logDetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_time", nullable = false, length = 19)
	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

}
